### ISSUE TITLE
Website upgrade

### ISSUE THREAD

**Issue by jbelien** [EqualStreetNames/equalstreetnames#231]
Let's use the PR #203 to update a few more things in the website since it might have an impact on the templates.

- [x] 1. Merge #219 to upgrade to [Bootstrap v5](https://getbootstrap.com/docs/5.0/)
- [x] 2. Make required changes following upgrade to [Bootstrap v5](https://getbootstrap.com/docs/5.0/) (see #232 + https://github.com/EqualStreetNames/equalstreetnames-template/pull/5)
- [x] 3. Merge #203 to add theme feature
- [x] 4. Upgrade to [Parcel v2](https://v2.parceljs.org/) (since Parcel v1 is now deprecated) ; already used by global website (see #233 + https://github.com/EqualStreetNames/equalstreetnames-template/pull/6)

**Comment by RobinLinde** [comment]
@jbelien
[These](https://github.com/EqualStreetNames/equalstreetnames-groningen/commit/acd27db9009365e9eb14a429452d30a95f400336) are the changes I've currently made for compatibility with Bootstrap 5.
In short:

- Change `*-right` to `*-end`
- Change `ml-auto` to `ms-auto`
- Change `data-*` to `data-bs-*`
- Add a container to the navbar
- Updated close button for modal

Popup would probably also need some work, since `.media` is [dropped](https://getbootstrap.com/docs/5.0/migration/#grid-updates)

**Comment by jbelien** [comment]
Upgrades have been deployed for Brussels ! 🚀 
Updating all the other cities right now! 💪

**Comment by jbelien** [comment]
Took a while but all repositories have been update and PR have been opened !

**Comment by jbelien** [comment]
Ping me if there is any issue !
